### ISSUE TITLE
Cannot find the collated folder in main. 

### ISSUE THREAD

**Issue by nirandiw** [CS2103JAN2017-T09-B1/main#107]
Where is your collated code folder? I need the collated code to provide feedback.

**Comment by senyuuri** [comment]
Hi nirandiw, you can find the collated folder in the develop branch. We'll merge it into master branch in our next release. Thank you.

**Comment by nirandiw** [comment]
Please merge the collated folder today if possible with the master branch. Then there is enough time for me to give you feedback on your code and you can update the code accordingly. This is an important step in order to make sure your coding standards are as expected. Therefore, please try to merge the collated code with the master branch today.

**Comment by senyuuri** [comment]
Okay we've updated the collate folder in master. Thank you.
